[package]
name = "konou/lab-toying"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@^1.4"
components = "sleitnick/component@2.4.6"
promise = "evaera/promise@4.0.0"