[package]
name = "wnace/lab-toying"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
link = "overlinejunior/link@0.1.2"
fusion = "elttob/fusion@0.2.0"